#!/usr/bin/env bash
# This is about alot of things 


# Set the IFS to ":" to split fields in /etc/passwd
IFS=":"

# Read /etc/passwd line by line
while read -r username password uid gid info home shell; do
    # Check if the UID is greater than or equal to 1000 (typical range for user accounts)
    if [ "$uid" -ge 1000 ]; then
        echo "The user $username is part of the group $gid gang,"
        echo "lives in $home and rides $shell."
        echo "USER ID's place is protected by the passcode $password."
        echo "More info about the user here: $info"
        echo
    fi
done < /etc/passwd

