#!/usr/bin/env bash
# This is a script printing Best School and this
count=0
while [ $count -lt 10 ]
do
  
  count=$((count + 1))

  
  if [ $count -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
done

