#!/usr/bin/env bash
# This is for hours and minutes
hour=0
minute=1

while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        minute=$((minute + 1))
        if [ $minute -eq 60 ]; then
            minute=0
            hour=$((hour + 1))
        fi
    done
    minute=1
    hour=$((hour + 1))
done | head -n 70

