#!/usr/bin/env bash
#THis is a bit harder terminated
#!/bin/bash

# Check if the process is running
if pgrep -x "4-to_infinity_and_beyond" > /dev/null
then
    # If the process is running, stop it
    pkill -x "4-to_infinity_and_beyond"
    echo "Process '4-to_infinity_and_beyond' has been stopped."
else
    echo "Process '4-to_infinity_and_beyond' is not running."
fi

