#!/usr/bin/env bash
#Thsi id madd

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Register the SIGTERM signal handler
trap 'handle_sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

